### ISSUE TITLE
Multiple recipients option stopped working

### ISSUE THREAD

**Issue by holysock8** [deanishe/alfred-mailto#11]
Hi,

with the latest update, the functionality to use multiple recipients stopped working for me.

It is the same whether I add them by hitting tab between entering new recipients or when I use groups from my address book to send emails to (which ultimately end up in the same format with email@email.com, email2@email.com, .. etc.)

This worked without problem in the previous version

any ideas?

thanks a lot!

Log:

[2017-09-21 16:41:47][STDERR: input.scriptfilter] 16:41:47 workflow.py:2249 DEBUG    workflow version: 2.2.0
16:41:47 workflow.py:1657 DEBUG    reading settings from /Users/Robin/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-mailto/settings.json
16:41:47 workflow.py:2532 DEBUG    Update check not due
16:41:47 mailto.py:135 DEBUG    args : Namespace(action=u'search', query=u'')
16:41:47 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/all_apps.cpickle
16:41:47 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/system_default_app.cpickle
16:41:47 mailto.py:153 DEBUG    Searching contacts
16:41:47 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/__workflow_update_status.cpickle
16:41:47 workflow.py:2462 DEBUG    update_data: {u'available': False}
16:41:47 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/contacts.cpickle
16:41:47 workflow.py:2441 DEBUG    set last run version: 2.2.0
16:41:47 workflow.py:2290 DEBUG    workflow finished in 0.223 seconds
[2017-09-21 16:41:48][STDERR: input.scriptfilter] 16:41:48 workflow.py:2249 DEBUG    workflow version: 2.2.0
16:41:48 workflow.py:1657 DEBUG    reading settings from /Users/Robin/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-mailto/settings.json
16:41:48 workflow.py:2532 DEBUG    Update check not due
16:41:48 mailto.py:135 DEBUG    args : Namespace(action=u'search', query=u'Test')
16:41:48 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/all_apps.cpickle
16:41:48 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/system_default_app.cpickle
16:41:48 mailto.py:153 DEBUG    Searching contacts
16:41:48 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/__workflow_update_status.cpickle
16:41:48 workflow.py:2462 DEBUG    update_data: {u'available': False}
16:41:48 workflow.py:1884 DEBUG    loading cached data: /Users/Robin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-mailto/contacts.cpickle
16:41:48 mailto.py:333 DEBUG    existing : [] emails : [] invalid_emails : [] query : u'Test'
16:41:48 workflow.py:1657 DEBUG    reading settings from /Users/Robin/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-mailto/settings.json
16:41:48 mailto.py:210 DEBUG    1 matches for `Test`
16:41:48 workflow.py:2441 DEBUG    set last run version: 2.2.0
16:41:48 workflow.py:2290 DEBUG    workflow finished in 0.060 seconds
[2017-09-21 16:41:55][ERROR: action.script] 16:41:55 workflow.py:2249 DEBUG    workflow version: 2.2.0
16:41:55 workflow.py:1657 DEBUG    reading settings from /Users/Robin/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-mailto/settings.json
16:41:55 workflow.py:2532 DEBUG    Update check not due
usage: mailto.py [-h]
                 {search,config,edit_client_rules,setclient,toggle,compose,reload,update,help}
                 [query]
mailto.py: error: unrecognized arguments: Test@test.com, Test2@test.com, Test3@test.com, Test4@test.com'
16:41:55 workflow.py:2290 DEBUG    workflow finished in 0.026 seconds

**Comment by deanishe** [comment]
I did notice this but forgot to push the fix. Fixed in [v2.2.1](https://github.com/deanishe/alfred-mailto/tree/v2.2.1).

Enter `mailto workflow:update` in Alfred to grab the update.
