### ISSUE TITLE
07:30:38 workflow.py:2266 ERROR    add_item() got an unexpected keyword argument 'modifier_subtitles'

### ISSUE THREAD

**Issue by tooh** [deanishe/alfred-mailto#12]
I can select contacts, mailclient (apple mail) does not start due to error

Running version
---------- MailTo (2.3.0) ----------

**Comment by deanishe** [comment]
Thanks for finding the bug. Fixed in [v2.3.1](https://github.com/deanishe/alfred-mailto/releases/tag/v2.3.1).

**Comment by tooh** [comment]
Wow, thx for fixing !
