### ISSUE TITLE
Airmail Beta Version 2.1 (308) - addresses not populating

### ISSUE THREAD

**Issue by ChrisHonniball** [deanishe/alfred-mailto#4]
When the email is composed it is not populating email addresses in the latest Airmail Beta Version 2.1 (308). Running OS X v10.10.4 (14E17e).

**Comment by deanishe** [comment]
I'm afraid I don't own Airmail 2, so *I* can't add the required support.

The workflow is designed to make it fairly easy to add support for other email clients, provided their support for the `mailto:` scheme isn't too rubbish (it is exactly great in Airmail 1).

If you fancy trying that, please look at the [docs](http://www.deanishe.net/alfred-mailto/#other-clients) for v2 (of the workflow). And if you get it working, please let me know, so I can add it to the workflow by default.

**Comment by rudders** [comment]
The following in the client_rules.json fixed this problem for me. 

{
// Airmail Beta 2.1
	"it.bloop.airmail.beta10": {
           "spaces": false,
           "names": false,
           "mime": false,
           "no_commas": false,
           "inline_to": true	
     }
}

**Comment by ChrisHonniball** [comment]
@rudders Confirmed! Thanks :+1:

**Comment by deanishe** [comment]
@rudders Thanks very much for that.

I won't add it to the defaults because it would only apply to one specific beta version.
