### ISSUE TITLE
Going straight to the Main message body heading instead of Subject heading

### ISSUE THREAD

**Issue by gilgameshskytrooper** [deanishe/alfred-mailto#8]
I am using mailto to compose new messages on Airmail.

However, one thing I have noticed is that doing this takes me straight to the text body part, rather than the subject line.

Is there any way to fix this so that when composing a new message, I go into the subject field, and then I can tab into the main message body?

**Comment by deanishe** [comment]
The workflow simply passes a `mailto:` URL to the application. 

How the app handles it is completely out of the workflow's hands, I'm afraid. 

As a result, this is something you should take up with Bloop.

IIRC, older versions of Airmail did focus the Subject field.
