### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kleinjm** [deanishe/alfred-mailto#9]
![image](https://cloud.githubusercontent.com/assets/2565158/25209246/cca0536c-2547-11e7-9d33-957e21635875.png)
 I'm seeing some serious CPU cranking and it looks like your plugin is the cause.

**Comment by deanishe** [comment]
It's an issue with Sierra & Alfred-Workflow.

Run [this workflow](https://github.com/deanishe/alfred-fixum).

**Comment by kleinjm** [comment]
Thanks a lot!
